### ISSUE TITLE
Daily rain forecast with imperial units

### ISSUE THREAD

**Issue by gabrielm9999** [bugsounet/MMM-Weather#2]
Hello - Thank you very much for another super module!  I have implemented the module with imperial units and found an issue.  Here is my view:
![MMM-Weather imperial units](https://user-images.githubusercontent.com/72508332/97452798-7dbff980-190b-11eb-958c-9ea2a40514cf.png)
The rain forecast for Thursday is 45.66 in/hr, which translates to 1.2 m/hr.  That is some major flooding!
I manually did a OpenWeatherMap API call resulting in the following:
![OWM-json](https://user-images.githubusercontent.com/72508332/97453240-ef984300-190b-11eb-8bc1-d982b570a657.png)
Therefore the value is correct, but it appears the units are off.
Looking at the API docs [here](https://openweathermap.org/api/one-call-api), the documentation describes the field as:
**daily.rain (where available) Precipitation volume, mm**
Therefore there may be 2 issues:
1. There is no unit conversion.  **daily.rain** is always in metric, and
2. The amount is total rain for the day, not rain/hr.

Many thanks again for a great module!

**Comment by bugsounet** [comment]
thx for report. i will see what happen

maybe i have missed to convert :p

**Comment by gabrielm9999** [comment]
Many thanks @bugsounet.  I've attached one additional screen shot with active rain:
![MMM-Weather imperial units2](https://user-images.githubusercontent.com/72508332/97580989-685dd480-19ca-11eb-8d6d-2b180265c5d2.png)
The current rain amount should be 1.62mm/hr, or (1.62/25.4)in/hr or 0.06in/hr. 
I believe the daily forecast shows total rain for the day.

Many thanks!

**Comment by bugsounet** [comment]
I my code and I forget to convert to it ;)

I will apply the rule soon ;)

**Comment by bugsounet** [comment]
corrected and commit

> I believe the daily forecast shows total rain for the day.

for the current weather value, i don't use daily api value, i use current api value like wind, temp actual, ...

**Comment by gabrielm9999** [comment]
@bugsounet I downloaded the dev branch and the fixed worked.  Thanks!
